version: 2.1

orbs:
  node: circleci/node@7.0.0

jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests
          command: npm run test
      - run:
          name: Build app
          command: npm run build
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

workflows:
  version: 2
  build_test:
    jobs:
      - build_and_test
